In [6]:
import numpy as np
a = np.random.random((3,2,4))

In [7]:
a


array([[[0.73114232, 0.34989016, 0.30407681, 0.9371351 ],
        [0.70428294, 0.80443721, 0.09150653, 0.63571029]],

       [[0.42838497, 0.89100314, 0.56576615, 0.89816407],
        [0.05034035, 0.79390821, 0.88972848, 0.49212353]],

       [[0.14830009, 0.82359273, 0.65764545, 0.25382229],
        [0.81058088, 0.21801537, 0.70612689, 0.39812216]]])

In [9]:
a.shape

(3, 2, 4)

In [10]:
a.size

24

In [12]:
b = np.random.random((5,2,3))

In [13]:
b.shape

(5, 2, 3)

In [14]:
b.size

30

In [18]:
c = np.random.random((2,3,4,1))

In [19]:
c

array([[[[0.24197651],
         [0.35582596],
         [0.75030636],
         [0.36596751]],

        [[0.54262182],
         [0.37511363],
         [0.18866726],
         [0.9965437 ]],

        [[0.55387782],
         [0.50126301],
         [0.48936313],
         [0.92735971]]],


       [[[0.76352275],
         [0.74768909],
         [0.83418174],
         [0.28182071]],

        [[0.95667755],
         [0.32475473],
         [0.78023564],
         [0.84388821]],

        [[0.38686738],
         [0.12232178],
         [0.85212051],
         [0.34532855]]]])

In [26]:
a = np.random.random((5,3))
a


array([[0.1330154 , 0.83236405, 0.87330945],
       [0.10754106, 0.29188441, 0.18990518],
       [0.38052032, 0.6690367 , 0.22584041],
       [0.21437211, 0.3301036 , 0.7096117 ],
       [0.4679468 , 0.51857036, 0.15369665]])

In [27]:
a[0]

array([0.1330154 , 0.83236405, 0.87330945])

In [28]:
a[1]

array([0.10754106, 0.29188441, 0.18990518])

In [29]:
a[:,0]

array([0.1330154 , 0.10754106, 0.38052032, 0.21437211, 0.4679468 ])

In [30]:
a[:]

array([[0.1330154 , 0.83236405, 0.87330945],
       [0.10754106, 0.29188441, 0.18990518],
       [0.38052032, 0.6690367 , 0.22584041],
       [0.21437211, 0.3301036 , 0.7096117 ],
       [0.4679468 , 0.51857036, 0.15369665]])

In [32]:
a[1:3]

array([[0.10754106, 0.29188441, 0.18990518],
       [0.38052032, 0.6690367 , 0.22584041]])

In [35]:
a[3,:]

array([0.21437211, 0.3301036 , 0.7096117 ])

In [36]:
lst = list(range(10))
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
lst[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
lst_nested = [[1,2,3],[4,5,6],[7,8,9]]


In [40]:
d = np.array(lst_nested)

In [41]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
d[2,:]

array([7, 8, 9])

In [44]:
d[:,2]

array([3, 6, 9])

In [47]:
np.sum(d)

45

In [48]:
np.sum(d, axis=0)

array([12, 15, 18])

In [50]:
np.sum(d, axis=1)

array([ 6, 15, 24])

In [51]:
np.mean(d)

5.0

In [52]:
np.mean(d[0,:])

2.0

calculations between arrays

In [58]:
x = np.random.random((3,4))
print(x)

[[0.9120049  0.25335511 0.76229475 0.97086366]
 [0.76127731 0.38374531 0.46042365 0.76016051]
 [0.98612131 0.2671731  0.6163951  0.70349554]]


In [59]:
y = np.random.random((3,4))
print(y)

[[0.02151567 0.86759032 0.06056598 0.47067969]
 [0.44847524 0.71040302 0.09812131 0.69868144]
 [0.08373921 0.89896526 0.48109629 0.66942752]]


In [61]:
x_plus_y = np.add(x,y)
x_plus_y

array([[0.93352057, 1.12094542, 0.82286073, 1.44154335],
       [1.20975255, 1.09414832, 0.55854496, 1.45884194],
       [1.06986052, 1.16613836, 1.0974914 , 1.37292306]])

In [64]:
x_times_y = np.multiply(x,y)
x_times_y

array([[0.0196224 , 0.21980844, 0.04616913, 0.4569658 ],
       [0.34141402, 0.27261382, 0.04517737, 0.53111004],
       [0.08257702, 0.24017933, 0.2965454 , 0.47093927]])