In [1]:
lst = [2,3,6,7]


In [2]:
import numpy as np

In [10]:
a = np.random.random((4))

In [11]:
a

array([0.95577943, 0.14630307, 0.99071275, 0.6828614 ])

In [16]:
b = np.random.random((4,3))
b

array([[0.6705642 , 0.91932539, 0.33777766],
       [0.48407539, 0.90330033, 0.2468332 ],
       [0.01291652, 0.00923909, 0.96434799],
       [0.37024147, 0.65808151, 0.59895013]])

In [18]:
b.shape

(4, 3)

In [19]:
b.size

12

In [21]:
c = np.random.random((2,3,4,1))
c

array([[[[0.26803459],
         [0.32562284],
         [0.35155495],
         [0.22969092]],

        [[0.28793975],
         [0.68071379],
         [0.26753378],
         [0.23364784]],

        [[0.2305656 ],
         [0.38378533],
         [0.58802628],
         [0.44535175]]],


       [[[0.13266285],
         [0.78495641],
         [0.88927115],
         [0.55767053]],

        [[0.59268675],
         [0.80541246],
         [0.43674099],
         [0.47153553]],

        [[0.09099503],
         [0.39491084],
         [0.9512262 ],
         [0.38334768]]]])

In [22]:
d = np.random.random((2,3,4,2))
d

array([[[[0.92705606, 0.51178216],
         [0.27278703, 0.86767557],
         [0.70927171, 0.61577069],
         [0.86878635, 0.72489694]],

        [[0.42160911, 0.40099776],
         [0.14795006, 0.3217682 ],
         [0.04238888, 0.7739495 ],
         [0.32749715, 0.98391918]],

        [[0.52393615, 0.64596428],
         [0.62659079, 0.46615716],
         [0.32859947, 0.12445744],
         [0.50124936, 0.20219239]]],


       [[[0.94090498, 0.00237601],
         [0.81197201, 0.14885148],
         [0.66457937, 0.46070839],
         [0.73815403, 0.46514743]],

        [[0.43246674, 0.23585514],
         [0.92474652, 0.87318064],
         [0.14697713, 0.51453289],
         [0.40930891, 0.96439349]],

        [[0.44557675, 0.01843106],
         [0.24253161, 0.50970637],
         [0.24340195, 0.79863506],
         [0.16443369, 0.73494075]]]])

In [23]:
e = np.random.random((4,3,4,2))
e

array([[[[0.21941892, 0.5951155 ],
         [0.94575425, 0.93672067],
         [0.19059604, 0.21676586],
         [0.77369963, 0.60167568]],

        [[0.98581336, 0.1475363 ],
         [0.77975012, 0.33463407],
         [0.91346773, 0.00804559],
         [0.65816971, 0.8763422 ]],

        [[0.27865618, 0.69624113],
         [0.96947744, 0.02075724],
         [0.71739699, 0.43052867],
         [0.73794523, 0.96237845]]],


       [[[0.06963473, 0.87869324],
         [0.83941899, 0.43905434],
         [0.63304204, 0.23193852],
         [0.35764789, 0.35651348]],

        [[0.33728045, 0.68929731],
         [0.36262554, 0.04623203],
         [0.88804672, 0.50814937],
         [0.19796261, 0.0310968 ]],

        [[0.37045221, 0.49384197],
         [0.30409065, 0.46799431],
         [0.34119807, 0.5858687 ],
         [0.18010747, 0.75262447]]],


       [[[0.36778656, 0.89788113],
         [0.48240638, 0.79845148],
         [0.46357581, 0.01919904],
         [0.07895806, 0.39519256]],

  

In [24]:
e = np.random.random((1,3,4,2))
e

array([[[[4.56133276e-01, 7.57646961e-01],
         [8.87358712e-01, 2.32367624e-04],
         [7.89342862e-01, 9.17207428e-01],
         [3.14217123e-02, 7.82399995e-01]],

        [[9.17497313e-01, 2.34600500e-01],
         [9.00646488e-01, 3.46315677e-01],
         [7.15813507e-01, 5.52510143e-01],
         [2.84967108e-01, 7.62426119e-02]],

        [[1.95568012e-01, 4.05027319e-01],
         [4.55992128e-01, 1.69875398e-01],
         [5.68073144e-01, 6.82175051e-01],
         [9.94461384e-01, 6.15318872e-01]]]])

In [29]:
f = np.random.random((0,6,4,2))
f

array([], shape=(0, 6, 4, 2), dtype=float64)

In [30]:
a = np.random.random((5,3))
a

array([[0.06383375, 0.05434549, 0.20705741],
       [0.2808541 , 0.72413224, 0.17153833],
       [0.75729412, 0.54297369, 0.01052004],
       [0.01154239, 0.19627639, 0.95861698],
       [0.83318822, 0.58051746, 0.60158362]])

In [31]:
a[0]

array([0.06383375, 0.05434549, 0.20705741])

In [32]:
a[0,:]

array([0.06383375, 0.05434549, 0.20705741])

In [33]:
a[1,:]

array([0.2808541 , 0.72413224, 0.17153833])

In [35]:
a[:,1]

array([0.05434549, 0.72413224, 0.54297369, 0.19627639, 0.58051746])

In [36]:
a[:,0:2]

array([[0.06383375, 0.05434549],
       [0.2808541 , 0.72413224],
       [0.75729412, 0.54297369],
       [0.01154239, 0.19627639],
       [0.83318822, 0.58051746]])

In [37]:
a[0:2,1]

array([0.05434549, 0.72413224])

In [38]:
a

array([[0.06383375, 0.05434549, 0.20705741],
       [0.2808541 , 0.72413224, 0.17153833],
       [0.75729412, 0.54297369, 0.01052004],
       [0.01154239, 0.19627639, 0.95861698],
       [0.83318822, 0.58051746, 0.60158362]])

In [39]:
a[:]

array([[0.06383375, 0.05434549, 0.20705741],
       [0.2808541 , 0.72413224, 0.17153833],
       [0.75729412, 0.54297369, 0.01052004],
       [0.01154239, 0.19627639, 0.95861698],
       [0.83318822, 0.58051746, 0.60158362]])

In [40]:
a[1:3]

array([[0.2808541 , 0.72413224, 0.17153833],
       [0.75729412, 0.54297369, 0.01052004]])

In [41]:
a[1:3,2]

array([0.17153833, 0.01052004])

In [44]:
lst2 = list(range(10))
lst2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
lst2[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
nested_list = [[1,2,3], [4,5,6], [7,8,9]]
nested_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [48]:
len(nested_list)

3

In [49]:
nested_list[0]

[1, 2, 3]

In [50]:
g = np.array(nested_list)
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
g[2,-1]

9

In [52]:
g[-1,-1]

9

In [53]:
list1 = [2,3,5,9]

In [55]:
array1 = np.array(list1)
array1

array([2, 3, 5, 9])

In [56]:
array1.shape

(4,)

In [57]:
g.shape

(3, 3)

In [58]:
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
g[1:2,1]

array([5])

In [60]:
g[1:2,1:2]

array([[5]])

In [61]:
g[1:2,1]

array([5])

In [62]:
g[1:3,1]

array([5, 8])

In [63]:
g[1:,1]

array([5, 8])

In [64]:
g[2,:3]

array([7, 8, 9])

In [65]:
g[2,:2]

array([7, 8])

In [66]:
g[2,0:2]

array([7, 8])

In [67]:
h = np.sum(g)
h

45

In [68]:
g


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
i = np.sum(g, axis=0)
i

array([12, 15, 18])

In [71]:
j = np.sum(g, axis=1)
j[0]

6

In [72]:
j

array([ 6, 15, 24])

In [75]:
k = np.mean(g)
k

5.0

In [77]:
l = np.mean(g, axis=1)
l

array([2., 5., 8.])

In [78]:
l[1]

5.0

In [79]:
np.mean(g[0,:])

2.0

In [80]:
np.mean(g[:,1])

5.0

In [81]:
np.mean(g[:,2])

6.0

In [82]:
my_selection = g[:,2]
my_selection

array([3, 6, 9])

In [83]:
np.mean(my_selection)

6.0

In [87]:
matrix1 = np.random.random((3,4))
matrix1

array([[0.83345608, 0.66454779, 0.88837341, 0.44547005],
       [0.96938672, 0.58801111, 0.06177152, 0.85052411],
       [0.18318601, 0.65853555, 0.21818555, 0.00662365]])

In [89]:
matrix2 = np.random.random((3,4))
matrix2

array([[0.26045886, 0.12173484, 0.97581117, 0.49909565],
       [0.33333034, 0.61297193, 0.76172695, 0.16238624],
       [0.02045527, 0.71916992, 0.95577928, 0.24836996]])

In [90]:
a1_plus_a2 = np.add(matrix1, matrix2)
a1_plus_a2

array([[1.09391494, 0.78628263, 1.86418458, 0.94456571],
       [1.30271706, 1.20098304, 0.82349847, 1.01291035],
       [0.20364128, 1.37770546, 1.17396483, 0.25499361]])

In [92]:
b1list = [[1,4],[5,6]]
b1=np.array(b1list)
b1

array([[1, 4],
       [5, 6]])

In [101]:
c1list = [[2,3],[7,8]]
c1=np.array(c1list)
c1

array([[2, 3],
       [7, 8]])

In [102]:
b1

array([[1, 4],
       [5, 6]])

In [103]:
c1

array([[2, 3],
       [7, 8]])

In [104]:
np.add(b1, c1)

array([[ 3,  7],
       [12, 14]])

In [105]:
b1.shape

(2, 2)

In [106]:
c1.shape

(2, 2)

In [107]:
b1.size

4

In [108]:
b1

array([[1, 4],
       [5, 6]])

In [109]:
c1

array([[2, 3],
       [7, 8]])

In [110]:
np.multiply(b1,c1)

array([[ 2, 12],
       [35, 48]])

In [111]:
b1 * c1

array([[ 2, 12],
       [35, 48]])

In [112]:
b1 + c1

array([[ 3,  7],
       [12, 14]])

In [113]:
(2*b1) + c1

array([[ 4, 11],
       [17, 20]])

In [114]:
2*b1 + 2*c1 - 1

array([[ 5, 13],
       [23, 27]])

In [115]:
b1

array([[1, 4],
       [5, 6]])

In [118]:
b1 - 1

array([[0, 3],
       [4, 5]])

In [120]:
first_column_c1 = c1[:,0]

In [121]:
first_column_b1 = b1[:,0]

In [122]:
b1

array([[1, 4],
       [5, 6]])

In [123]:
c1

array([[2, 3],
       [7, 8]])

In [124]:
first_column_b1 * first_column_c1

array([ 2, 35])

In [125]:
c1[:,0] * b1[:,0]

array([ 2, 35])

In [128]:
result = c1 * b1
result

array([[ 2, 12],
       [35, 48]])

In [129]:
result[:,0]

array([ 2, 35])

In [130]:
c1[:,0] * c1[0,:]

array([ 4, 21])

In [131]:
c1[:,0]

array([2, 7])

In [132]:
c1[0,:]

array([2, 3])

In [133]:
c1[:,0] * c1[0,:]

array([ 4, 21])

In [134]:
c1

array([[2, 3],
       [7, 8]])

In [135]:
b1

array([[1, 4],
       [5, 6]])

In [136]:
c1[:,0] * b1[:,0]

array([ 2, 35])

In [137]:
c1


array([[2, 3],
       [7, 8]])

In [138]:
b1

array([[1, 4],
       [5, 6]])

In [139]:
v1 =np.arange(2, 11).reshape(3,3)

In [140]:
v1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [144]:
v2 =np.arange(2, 11).reshape(3,3) + 1

In [145]:
v2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [151]:
for i in range( v1.shape[0] ):
    print(i)

0
1
2


In [153]:
v1 = matrix1
v1

array([[0.83345608, 0.66454779, 0.88837341, 0.44547005],
       [0.96938672, 0.58801111, 0.06177152, 0.85052411],
       [0.18318601, 0.65853555, 0.21818555, 0.00662365]])

In [155]:
for i in range( v1.shape[0] ):
    print(i)

0
1
2


In [156]:
for i in range( v1.shape[1] ):
    print(i)

0
1
2
3


In [158]:
v1 =np.arange(2, 11).reshape(3,3)
v1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [164]:
for i in range( v1.shape[1] ):
    print(i)
    print(v1[:,i])
    print(v2[i,:])
    print(v1[:,i] * v2[i,:])
   

0
[2 5 8]
[3 4 5]
[ 6 20 40]
1
[3 6 9]
[6 7 8]
[18 42 72]
2
[ 4  7 10]
[ 9 10 11]
[ 36  70 110]


In [173]:
v1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [171]:
matrix2

array([[0.26045886, 0.12173484, 0.97581117, 0.49909565],
       [0.33333034, 0.61297193, 0.76172695, 0.16238624],
       [0.02045527, 0.71916992, 0.95577928, 0.24836996]])

In [172]:
matrix2.transpose()

array([[0.26045886, 0.33333034, 0.02045527],
       [0.12173484, 0.61297193, 0.71916992],
       [0.97581117, 0.76172695, 0.95577928],
       [0.49909565, 0.16238624, 0.24836996]])

In [174]:
v1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [175]:
v1.reshape(9,1)

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [176]:
v1.reshape(9,2)

ValueError: cannot reshape array of size 9 into shape (9,2)